#!/usr/bin/env python3
"""Compile country-only opening law, religion, and technology profiles."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/scenario/opening_profiles.json"
OUTPUT = ROOT / "yongchang_world/common/history/countries/zzz_ywc_opening_profiles.txt"
DEFAULT_GAME_ROOT = Path(r"E:\SteamLibrary\steamapps\common\Victoria 3")


def ids_from_files(paths: list[Path]) -> set[str]:
    ids: set[str] = set()
    for path in paths:
        text = path.read_text(encoding="utf-8-sig")
        ids.update(re.findall(r"(?m)^\s*([A-Za-z][A-Za-z0-9_]*)\s*=\s*\{", text))
    return ids


def validate(data: dict, game_root: Path) -> None:
    registry = json.loads((ROOT / "data/scenario/tag_registry.json").read_text(encoding="utf-8-sig"))
    profiles = data.get("countries", {})
    reused = set(data.get("reused_tags", []))
    reused_aliases = {row.get("source_tag") for row in registry.get("countries", []) if row.get("mode") == "reuse"}
    if reused - (set(registry["reuse"]) | reused_aliases):
        raise ValueError(f"profiles mark unknown reused tags: {sorted(reused - set(registry['reuse']) - reused_aliases)}")
    if set(profiles) != set(registry["new"]) | reused:
        raise ValueError("opening profiles must cover all new tags and explicitly listed reused tags")

    countries = ids_from_files(
        list((game_root / "game/common/country_definitions").glob("*.txt"))
        + list((ROOT / "yongchang_world/common/country_definitions").glob("*.txt"))
    )
    religions = ids_from_files(list((game_root / "game/common/religions").glob("*.txt")))
    cultures = ids_from_files(list((game_root / "game/common/cultures").glob("*.txt")))
    technologies = ids_from_files(list((game_root / "game/common/technology").rglob("*.txt")))

    for tag, row in profiles.items():
        if tag not in countries:
            raise ValueError(f"unknown country tag: {tag}")
        primary = row.get("primary_cultures")
        if not isinstance(primary, list) or not primary or len(primary) > 2:
            raise ValueError(f"{tag}: expected one or two politically grounded primary cultures")
        invalid = set(primary) - cultures
        if invalid:
            raise ValueError(f"{tag}: unknown cultures: {sorted(invalid)}")
        religion = row.get("state_religion")
        if religion not in religions:
            raise ValueError(f"{tag}: unknown state religion: {religion}")
        if row.get("government") not in {"monarchy", "theocracy"}:
            raise ValueError(f"{tag}: unsupported government profile")
        focus = row.get("technology_focus")
        if not isinstance(focus, list) or not focus:
            raise ValueError(f"{tag}: missing starting technology focus")
        invalid = set(focus) - technologies
        if invalid:
            raise ValueError(f"{tag}: unknown technologies: {sorted(invalid)}")
        if not isinstance(row.get("state_religion_law"), bool):
            raise ValueError(f"{tag}: state_religion_law must be boolean")
        for law in row.get("laws", []):
            if not re.fullmatch(r"law_[a-z0-9_]+", law):
                raise ValueError(f"{tag}: invalid law id: {law}")


def render(data: dict) -> str:
    lines = [
        "# Generated by tools/build_opening_profiles.py from data/scenario/opening_profiles.json.",
        "# Cultural, religious and research setup belongs to polities; pop history remains independent.",
        "COUNTRIES = {",
    ]
    for tag, row in sorted(data["countries"].items()):
        lines.extend([f"    c:{tag} ?= {{"])
        lines.append(f"        set_state_religion = rel:{row['state_religion']}")
        if row["state_religion_law"]:
            lines.append("        activate_law = law_type:law_state_religion")
        if row["government"] == "theocracy":
            lines.append("        activate_law = law_type:law_theocracy")
        lines.append("        set_tax_level = low")
        for technology in row["technology_focus"]:
            lines.append(f"        add_technology_researched = {technology}")
        for law in row.get("laws", []):
            lines.append(f"        activate_law = law_type:{law}")
        lines.extend(["    }", ""])
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, default=DEFAULT_GAME_ROOT)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    data = json.loads(DATA.read_text(encoding="utf-8-sig"))
    validate(data, args.game_root)
    expected = render(data)
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8-sig") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"stale generated file: {OUTPUT}", file=sys.stderr)
            return 1
        print(f"validated {len(data['countries'])} polity profiles")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8-sig", newline="")
    print(f"generated {OUTPUT} ({len(data['countries'])} polity profiles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
